### PR TITLE
FFT: separate exception

### LINKED ISSUE #145: Use actual error type instead of just string.
Like FunctionNotFound or InvalidParameter.

### PR DESCRIPTION
**Pull request by JTeeuwissen**
resolves #145

### CODE REVIEW

File: example/app/Main.hs [hunk 1]
```diff
@@ -22,16 +23,16 @@ main = do
 -- >>> evaluate (read "3") (read "4")
 -- Right 81.0
 evaluate :: Json -> Json -> Result Json
-evaluate base expo = evaluatorWithPow (read "{\"**\":[{\"var\":\"base\"}, {\"var\":\"exp\"}]}") (JsonObject [("base", base), ("exp", expo)])
+evaluate base expo = applyWithPow (read "{\"**\":[{\"var\":\"base\"}, {\"var\":\"exp\"}]}") (JsonObject [("base", base), ("exp", expo)])
```
Comment (GerardvSchie) [inline example/app/Main.hs:26]: Shouldnt this be named apply?

File: core/README.md [hunk 2]
```diff
@@ -20,18 +21,18 @@ main = do
 -- The two numbers are placed into an data object and given to the evaluator with the following logic:
 -- {"**":[{"var":"base"}, {"var":"exp"}]}
 -- >>> evaluate (read "3") (read "4")
--- 81
+-- Right 81.0
 evaluate :: Json -> Json -> Result Json
-evaluate base expo = evaluatorWithPow (read "{\"**\":[{\"var\":\"base\"}, {\"var\":\"exp\"}]}") (JsonObject [("base", base), ("exp", expo)])
+evaluate base expo = applyWithPow (read "{\"**\":[{\"var\":\"base\"}, {\"var\":\"exp\"}]}") (JsonObject [("base", base), ("exp", expo)])
```
Comment (GerardvSchie) [inline core/README.md:26]: Shouldnt this be apply?

**Review by GerardvSchie — APPROVED** [review]

**Review by GerardvSchie — APPROVED** [review]
